name: Deploy my protfolio application on dev server

on:
  push:
    branches:
      - v1.x

jobs:
  build:
    name: Dev deployment process
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/iamalamin/protfolio
            git pull origin v1.x

on:
  push:
    branches:
      - v2.x

jobs:
  any_name:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "GH_REPO"
          echo "GH_REPO_O"
          echo "GH_T"